// Funcionalidades o acciones dentro del Estado

export const GET_USERS = 'GET_USERS'
export const GET_PROFILES = 'GET_PROFILES'
export const GET_USER_PROFILES = 'GET_USER_PROFILES'
export const SET_USER_PROFILES = 'SET_USER_PROFILES'
export const SET_USER_CLASSES_TODAY = 'SET_USER_CLASSES_TODAY'
export const GET_USER_CLASSES_TODAY = 'GET_USER_CLASSES_TODAY'
export const SET_USER_DATE_TODAY = 'SET_USER_DATE_TODAY'
export const GET_USER_DATE_TODAY = 'GET_USER_DATE_TODAY'
