name: Build Test
on:
  push:
    branches:
      - 'feature/**'
      - 'bugfix/**'
      - 'bug/**'
      - 'dev'
      - 'qa'
      - 'staging'
      - 'pre-qa'

jobs:
  build-test:
    runs-on: self-hosted
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Build and push image'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - run: docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/uss/experiencia-digital/fronend-dev:latest